name: Webserver Script CI

on:
    push:
      branches: 
        - main
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *'
        - cron: '2 0 * * *'
        
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
       - name: Check out repository
         uses: actions/checkout@v4
       - name: Brief file info
         run: cat config/webserver.conf
       - name: Script test
         run: ./check-config.sh
