name: Sys Workflow Basics

env:
    REPORT_DIR: "reports" # Global report variable
    APP_NAME: "sysworkflow"
    REGION: "Greenland"

on:
    push:
      branches: 
        - main
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *'
        - cron: '0 17 * * *'
        
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
       - name: Check out repository
         uses: actions/checkout@v4
       - name: Date
         run: date
       - name: Display Kernel/System Info
         run: uname -a
       - name: Display working directory
         run: pwd
       - name: List Directory contents
         env:
           LSdir: ls -la    
         run: $LSdir
       - name: Report -p {{ env.REPORT_DIR }}
         run: mkdir reports
       - name: System report
         run: touch system-report.txt
       - name: Data for report
         run: |
              date > reports/system-report.txt
              uname -a >> ${{ env.REPORT_DIR }}/system-report.txt
              pwd >> ${{ env.REPORT_DIR }}/system-report.txt
              ls -la >> ${{ env.REPORT_DIR }}/system-report.txt
       - name: runtime info
         run: touch reports/runtime-info.txt
       - name: Data for runtime
         run: 
               |
               ${{ env.APP_NAME }} > /{{ env.REPORT_DIR }}/runtime-info.txt
               ${{ env.REGION }} > //{{ env.REPORT_DIR }}/runtime-info.txt
       
